`timescale 1ns/1ps

module frame_dma_rx_aurora_ufc_wrap #(
    parameter integer UFC_AXIS_DATA_W = 64
)(
    input             aclk,
    input             aresetn,
    input      [511:0] rx_axis_tdata,
    input              rx_axis_tvalid,
    output             rx_axis_tready,
    input              tx_axis_aclk,
    input              tx_axis_aresetn,
    output     [511:0] tx_axis_tdata,
    output             tx_axis_tvalid,
    input              tx_axis_tready,
    input      [31:0]  s_axil_awaddr,
    input              s_axil_awvalid,
    output             s_axil_awready,
    input      [31:0]  s_axil_wdata,
    input      [3:0]   s_axil_wstrb,
    input              s_axil_wvalid,
    output             s_axil_wready,
    output      [1:0]  s_axil_bresp,
    output             s_axil_bvalid,
    input              s_axil_bready,
    input      [31:0]  s_axil_araddr,
    input              s_axil_arvalid,
    output             s_axil_arready,
    output     [31:0]  s_axil_rdata,
    output      [1:0]  s_axil_rresp,
    output             s_axil_rvalid,
    input              s_axil_rready,
    output     [31:0] m_axi_awaddr,
    output      [7:0]  m_axi_awlen,
    output      [2:0]  m_axi_awsize,
    output      [1:0]  m_axi_awburst,
    output             m_axi_awvalid,
    input              m_axi_awready,
    output     [63:0]  m_axi_wdata,
    output      [7:0]  m_axi_wstrb,
    output             m_axi_wlast,
    output             m_axi_wvalid,
    input              m_axi_wready,
    input       [1:0]  m_axi_bresp,
    input              m_axi_bvalid,
    output             m_axi_bready,
    output      [31:0] m_axi_araddr,
    output      [7:0]  m_axi_arlen,
    output      [2:0]  m_axi_arsize,
    output      [1:0]  m_axi_arburst,
    output             m_axi_arvalid,
    input              m_axi_arready,
    input      [63:0]  m_axi_rdata,
    input      [1:0]   m_axi_rresp,
    input              m_axi_rlast,
    input              m_axi_rvalid,
    output             m_axi_rready,
    output [UFC_AXIS_DATA_W-1:0] aurora_ufc_tx_tdata,
    output             aurora_ufc_tx_tvalid,
    input              aurora_ufc_tx_tready,
    output             aurora_ufc_tx_tlast,
    input  [UFC_AXIS_DATA_W-1:0] aurora_ufc_rx_tdata,
    input              aurora_ufc_rx_tvalid,
    output             aurora_ufc_rx_tready,
    input              aurora_ufc_rx_tlast,
    output             aurora_ufc_rx_drop_pulse,
    output      [3:0]  aurora_ufc_rx_drop_reason,
    output             irq
);

wire        ufc_tx_valid;
wire        ufc_tx_ready;
wire [7:0]  ufc_tx_opcode;
wire [15:0] ufc_tx_flow_id;
wire [31:0] ufc_tx_arg0;
wire [31:0] ufc_tx_arg1;
wire        ufc_rx_valid;
wire        ufc_rx_ready;
wire [7:0]  ufc_rx_opcode;
wire [15:0] ufc_rx_flow_id;
wire [31:0] ufc_rx_arg0;
wire [31:0] ufc_rx_arg1;

frame_dma_wrapper u_dma_wrapper (
    .aclk(aclk),
    .aresetn(aresetn),
    .tx_axis_aclk(tx_axis_aclk),
    .tx_axis_aresetn(tx_axis_aresetn),
    .rx_axis_tdata(rx_axis_tdata),
    .rx_axis_tvalid(rx_axis_tvalid),
    .rx_axis_tready(rx_axis_tready),
    .tx_axis_tdata(tx_axis_tdata),
    .tx_axis_tvalid(tx_axis_tvalid),
    .tx_axis_tready(tx_axis_tready),
    .s_axil_awaddr(s_axil_awaddr),
    .s_axil_awvalid(s_axil_awvalid),
    .s_axil_awready(s_axil_awready),
    .s_axil_wdata(s_axil_wdata),
    .s_axil_wstrb(s_axil_wstrb),
    .s_axil_wvalid(s_axil_wvalid),
    .s_axil_wready(s_axil_wready),
    .s_axil_bresp(s_axil_bresp),
    .s_axil_bvalid(s_axil_bvalid),
    .s_axil_bready(s_axil_bready),
    .s_axil_araddr(s_axil_araddr),
    .s_axil_arvalid(s_axil_arvalid),
    .s_axil_arready(s_axil_arready),
    .s_axil_rdata(s_axil_rdata),
    .s_axil_rresp(s_axil_rresp),
    .s_axil_rvalid(s_axil_rvalid),
    .s_axil_rready(s_axil_rready),
    .m_axi_awaddr(m_axi_awaddr),
    .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize),
    .m_axi_awburst(m_axi_awburst),
    .m_axi_awvalid(m_axi_awvalid),
    .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata),
    .m_axi_wstrb(m_axi_wstrb),
    .m_axi_wlast(m_axi_wlast),
    .m_axi_wvalid(m_axi_wvalid),
    .m_axi_wready(m_axi_wready),
    .m_axi_bresp(m_axi_bresp),
    .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .m_axi_araddr(m_axi_araddr),
    .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize),
    .m_axi_arburst(m_axi_arburst),
    .m_axi_arvalid(m_axi_arvalid),
    .m_axi_arready(m_axi_arready),
    .m_axi_rdata(m_axi_rdata),
    .m_axi_rresp(m_axi_rresp),
    .m_axi_rlast(m_axi_rlast),
    .m_axi_rvalid(m_axi_rvalid),
    .m_axi_rready(m_axi_rready),
    .ufc_tx_valid(ufc_tx_valid),
    .ufc_tx_ready(ufc_tx_ready),
    .ufc_tx_opcode(ufc_tx_opcode),
    .ufc_tx_flow_id(ufc_tx_flow_id),
    .ufc_tx_arg0(ufc_tx_arg0),
    .ufc_tx_arg1(ufc_tx_arg1),
    .ufc_rx_valid(ufc_rx_valid),
    .ufc_rx_ready(ufc_rx_ready),
    .ufc_rx_opcode(ufc_rx_opcode),
    .ufc_rx_flow_id(ufc_rx_flow_id),
    .ufc_rx_arg0(ufc_rx_arg0),
    .ufc_rx_arg1(ufc_rx_arg1),
    .irq(irq)
);

dma_aurora_ufc_adapter #(
    .UFC_AXIS_DATA_W(UFC_AXIS_DATA_W)
) u_ufc_adapter(
    .clk(aclk),
    .rstn(aresetn),
    .ufc_tx_valid(ufc_tx_valid),
    .ufc_tx_ready(ufc_tx_ready),
    .ufc_tx_opcode(ufc_tx_opcode),
    .ufc_tx_flow_id(ufc_tx_flow_id),
    .ufc_tx_arg0(ufc_tx_arg0),
    .ufc_tx_arg1(ufc_tx_arg1),
    .ufc_rx_valid(ufc_rx_valid),
    .ufc_rx_ready(ufc_rx_ready),
    .ufc_rx_opcode(ufc_rx_opcode),
    .ufc_rx_flow_id(ufc_rx_flow_id),
    .ufc_rx_arg0(ufc_rx_arg0),
    .ufc_rx_arg1(ufc_rx_arg1),
    .aurora_ufc_tx_tdata(aurora_ufc_tx_tdata),
    .aurora_ufc_tx_tvalid(aurora_ufc_tx_tvalid),
    .aurora_ufc_tx_tready(aurora_ufc_tx_tready),
    .aurora_ufc_tx_tlast(aurora_ufc_tx_tlast),
    .aurora_ufc_rx_tdata(aurora_ufc_rx_tdata),
    .aurora_ufc_rx_tvalid(aurora_ufc_rx_tvalid),
    .aurora_ufc_rx_tready(aurora_ufc_rx_tready),
    .aurora_ufc_rx_tlast(aurora_ufc_rx_tlast),
    .rx_drop_pulse(aurora_ufc_rx_drop_pulse),
    .rx_drop_reason(aurora_ufc_rx_drop_reason)
);

endmodule
