`timescale 1ns/1ps
`include "dma_defs.vh"

module slvc_dma_wrapper #(
    parameter integer SL_DATA_WIDTH = 512,
    parameter integer TX_RD_MAX_OUTSTANDING = `DMA_TX_RD_MAX_OUTSTANDING,
    parameter integer RX_WR_MAX_OUTSTANDING = `DMA_RX_WR_MAX_OUTSTANDING
)(
    input              sl_rx_aclk,
    input              sl_rx_aresetn,
    input      [SL_DATA_WIDTH-1:0] sl_rx_tdata,
    input              sl_rx_tvalid,
    output             sl_rx_tready,
    input              sl_tx_aclk,
    input              sl_tx_aresetn,
    output     [SL_DATA_WIDTH-1:0] sl_tx_tdata,
    output             sl_tx_tvalid,
    input              sl_tx_tready,
    input      [31:0]  s_axil_awaddr,
    input              s_axil_awvalid,
    output             s_axil_awready,
    input      [31:0]  s_axil_wdata,
    input      [3:0]   s_axil_wstrb,
    input              s_axil_wvalid,
    output             s_axil_wready,
    output      [1:0]  s_axil_bresp,
    output             s_axil_bvalid,
    input              s_axil_bready,
    input      [31:0]  s_axil_araddr,
    input              s_axil_arvalid,
    output             s_axil_arready,
    output     [31:0]  s_axil_rdata,
    output      [1:0]  s_axil_rresp,
    output             s_axil_rvalid,
    input              s_axil_rready,
    output     [31:0]  m_axi_awaddr,
    output      [7:0]  m_axi_awlen,
    output      [2:0]  m_axi_awsize,
    output      [1:0]  m_axi_awburst,
    output             m_axi_awvalid,
    input              m_axi_awready,
    output     [63:0]  m_axi_wdata,
    output      [7:0]  m_axi_wstrb,
    output             m_axi_wlast,
    output             m_axi_wvalid,
    input              m_axi_wready,
    input       [1:0]  m_axi_bresp,
    input              m_axi_bvalid,
    output             m_axi_bready,
    output      [31:0] m_axi_araddr,
    output      [7:0]  m_axi_arlen,
    output      [2:0]  m_axi_arsize,
    output      [1:0]  m_axi_arburst,
    output             m_axi_arvalid,
    input              m_axi_arready,
    input      [63:0]  m_axi_rdata,
    input      [1:0]   m_axi_rresp,
    input              m_axi_rlast,
    input              m_axi_rvalid,
    output             m_axi_rready,
    output             ctrl_msg_tx_valid,
    input              ctrl_msg_tx_ready,
    output      [7:0]  ctrl_msg_tx_opcode,
    output     [15:0]  ctrl_msg_tx_channel_id,
    output     [31:0]  ctrl_msg_tx_arg0,
    output     [31:0]  ctrl_msg_tx_arg1,
    input              ctrl_msg_rx_valid,
    output             ctrl_msg_rx_ready,
    input       [7:0]  ctrl_msg_rx_opcode,
    input      [15:0]  ctrl_msg_rx_channel_id,
    input      [31:0]  ctrl_msg_rx_arg0,
    input      [31:0]  ctrl_msg_rx_arg1,
    output             irq
);

initial begin
    if (SL_DATA_WIDTH != 512)
        $fatal(1, "slvc_dma_wrapper width parameterization is staged; only 512 is currently enabled");
end

frame_dma_wrapper #(
    .SL_DATA_WIDTH(SL_DATA_WIDTH),
    .TX_RD_MAX_OUTSTANDING(TX_RD_MAX_OUTSTANDING),
    .RX_WR_MAX_OUTSTANDING(RX_WR_MAX_OUTSTANDING)
) u_frame_dma_wrapper (
    .aclk(sl_rx_aclk),
    .aresetn(sl_rx_aresetn),
    .tx_axis_aclk(sl_tx_aclk),
    .tx_axis_aresetn(sl_tx_aresetn),
    .rx_axis_tdata(sl_rx_tdata),
    .rx_axis_tvalid(sl_rx_tvalid),
    .rx_axis_tready(sl_rx_tready),
    .tx_axis_tdata(sl_tx_tdata),
    .tx_axis_tvalid(sl_tx_tvalid),
    .tx_axis_tready(sl_tx_tready),
    .s_axil_awaddr(s_axil_awaddr),
    .s_axil_awvalid(s_axil_awvalid),
    .s_axil_awready(s_axil_awready),
    .s_axil_wdata(s_axil_wdata),
    .s_axil_wstrb(s_axil_wstrb),
    .s_axil_wvalid(s_axil_wvalid),
    .s_axil_wready(s_axil_wready),
    .s_axil_bresp(s_axil_bresp),
    .s_axil_bvalid(s_axil_bvalid),
    .s_axil_bready(s_axil_bready),
    .s_axil_araddr(s_axil_araddr),
    .s_axil_arvalid(s_axil_arvalid),
    .s_axil_arready(s_axil_arready),
    .s_axil_rdata(s_axil_rdata),
    .s_axil_rresp(s_axil_rresp),
    .s_axil_rvalid(s_axil_rvalid),
    .s_axil_rready(s_axil_rready),
    .m_axi_awaddr(m_axi_awaddr),
    .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize),
    .m_axi_awburst(m_axi_awburst),
    .m_axi_awvalid(m_axi_awvalid),
    .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata),
    .m_axi_wstrb(m_axi_wstrb),
    .m_axi_wlast(m_axi_wlast),
    .m_axi_wvalid(m_axi_wvalid),
    .m_axi_wready(m_axi_wready),
    .m_axi_bresp(m_axi_bresp),
    .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .m_axi_araddr(m_axi_araddr),
    .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize),
    .m_axi_arburst(m_axi_arburst),
    .m_axi_arvalid(m_axi_arvalid),
    .m_axi_arready(m_axi_arready),
    .m_axi_rdata(m_axi_rdata),
    .m_axi_rresp(m_axi_rresp),
    .m_axi_rlast(m_axi_rlast),
    .m_axi_rvalid(m_axi_rvalid),
    .m_axi_rready(m_axi_rready),
    .ufc_tx_valid(ctrl_msg_tx_valid),
    .ufc_tx_ready(ctrl_msg_tx_ready),
    .ufc_tx_opcode(ctrl_msg_tx_opcode),
    .ufc_tx_flow_id(ctrl_msg_tx_channel_id),
    .ufc_tx_arg0(ctrl_msg_tx_arg0),
    .ufc_tx_arg1(ctrl_msg_tx_arg1),
    .ufc_rx_valid(ctrl_msg_rx_valid),
    .ufc_rx_ready(ctrl_msg_rx_ready),
    .ufc_rx_opcode(ctrl_msg_rx_opcode),
    .ufc_rx_flow_id(ctrl_msg_rx_channel_id),
    .ufc_rx_arg0(ctrl_msg_rx_arg0),
    .ufc_rx_arg1(ctrl_msg_rx_arg1),
    .irq(irq)
);

endmodule
