# Current SLVC/UDP frame DMA dependency closure for FPGA OOC implementation.
rtl/dma_axis_register_slice.v
rtl/dma_axis_width_pack_512.v
rtl/dma_axis_skid_buffer.v
rtl/dma_async_fifo.v
rtl/dma_axis_async_fifo.v
rtl/dma_ctrl_msg_async_fifo.v
rtl/dma_payload_beat_ram.v
rtl/dma_rx_parser.v
rtl/dma_rx_parser_pipe.v
rtl/dma_rx_channel_match.v
rtl/dma_rx_payload_buffer.v
rtl/dma_rx_ingress_queue.v
rtl/dma_rx_fc_ingress_bank.v
rtl/dma_rx_fc_ctrl.v
rtl/dma_axi_write_engine.v
rtl/dma_tx_header_builder.v
rtl/dma_axi_read_prefetch.v
rtl/dma_tx_engine.v
rtl/dma_cq_writer.v
rtl/dma_cq_single_writer.v
rtl/dma_rx_write_arbiter.v
rtl/dma_ufc_mailbox.v
rtl/dma_axil_regs.v
rtl/dma_tx_channel_table.v
rtl/dma_rx_channel_table.v
rtl/dma_tx_desc_channel_table.v
rtl/dma_frame_payload_ram.v
rtl/dma_frame_shared_pool.v
rtl/dma_rx_frame_shared_adapter.v
rtl/dma_rx_ingress_source_selector.v
rtl/frame_dma_rx_top.v
rtl/frame_dma_rx_axis_width_frontend.v
rtl/frame_dma_wrapper.v
rtl/slvc_dma_wrapper.v
rtl/slvc_carrier_cdc_adapter.v
rtl/mcf_endpoint.v
